platform :ios, '10.0'

target 'CardGuru' do
  use_frameworks!
  inhibit_all_warnings!

pod 'Firebase/Auth'
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'CodableFirebase'
pod 'GoogleSignIn'
pod 'FBSDKLoginKit'
pod 'FacebookLogin'
pod 'SVProgressHUD'
pod 'Alamofire'
pod 'AlamofireImage', '~> 3.4'

end
